---
apiVersion: v1
kind: ConfigMap
metadata:
  name: member-a
  namespace: besu
  labels:
    app.kubernetes.io/name: besu
    app.kubernetes.io/component: member-a
data:
  config.toml: |-
    # network
    network-id="1337"

    # gas
    min-gas-price=0

    # data
    data-path="/data"
    logging="INFO"

    genesis-file="/config/genesis.json"
    host-whitelist=["*"]
    node-private-key-file="/keys/nodekey"

    # p2p
    p2p-host="0.0.0.0"
    p2p-port=30303
    max-peers=25

    # rpc
    rpc-http-enabled=true
    rpc-http-host="0.0.0.0"
    rpc-http-port=8545
    rpc-http-api=["ADMIN", "DEBUG", "NET", "ETH", "MINER", "WEB3", "QBFT", "CLIQUE", "EEA", "IBFT"]
    rpc-http-cors-origins=["all"]

    # ws
    rpc-ws-enabled=true
    rpc-ws-host="0.0.0.0"
    rpc-ws-port=8546
    rpc-ws-api=["ADMIN", "DEBUG", "NET", "ETH", "MINER", "WEB3", "QBFT", "CLIQUE", "EEA", "IBFT"]

    # graphql
    graphql-http-enabled=true
    graphql-http-host="0.0.0.0"
    graphql-http-port=8547
    graphql-http-cors-origins=["all"]

    # metrics
    metrics-enabled=true
    metrics-host="0.0.0.0"
    metrics-port=9545

    # privacy
    privacy-enabled=false
    privacy-url="http://localhost:9101"
    privacy-public-key-file="/keys/tessera.pub"

    # permissions
    permissions-nodes-config-file-enabled=true
    permissions-nodes-config-file="/config/permissioned-nodes.toml"

    # static nodes
    static-nodes-file="/config/static-nodes.json"

    # miner
    miner-enabled=false

  config.json: |
    {
      "useWhiteList": false,
      "jdbc": {
        "username": "sa",
        "password": "",
        "url": "jdbc:h2:/data/tessera/db;MODE=Oracle;TRACE_LEVEL_SYSTEM_OUT=0",
        "autoCreateTables": true
      },
      "serverConfigs":[
      {
        "app":"ThirdParty",
        "enabled": true,
        "serverAddress": "http://member-a-0.member-a.besu.svc.cluster.local:9080",
        "communicationType" : "REST"
      },
      {
        "app":"Q2T",
        "enabled": true,
        "serverAddress": "http://localhost:9101",
        "sslConfig": {
          "tls": "OFF"
        },
        "communicationType" : "REST"
      },
      {
        "app":"P2P",
        "enabled": true,
        "serverAddress": "http://member-a-0.member-a.besu.svc.cluster.local:9000",
        "sslConfig": {
          "tls": "OFF"
        },
        "communicationType" : "REST"
      }
      ],
      "peer": [
        {
          "url": "http://member-a-0.member-a.besu.svc.cluster.local:9000",
          "url": "http://member-a-1.member-a.besu.svc.cluster.local:9000"
        }
      ],
      "keys": {
        "keyData": [
          {
            "privateKeyPath": "/keys/tessera.key",
            "publicKeyPath": "/keys/tessera.pub"
          }
        ]
      },
      "alwaysSendTo": []
    }
