---
apiVersion: v1
kind: ConfigMap
metadata:
  name: validator
  namespace: besu
  labels:
    app.kubernetes.io/name: besu
    app.kubernetes.io/component: validator
data:
  config.toml: |-
    # network
    network-id="1337"

    # gas
    min-gas-price=0

    # data
    data-path="/data"
    logging="INFO"

    genesis-file="/config/genesis.json"
    host-whitelist=["*"]
    node-private-key-file="/keys/nodekey"

    # p2p
    p2p-host="0.0.0.0"
    p2p-port=30303
    max-peers=25

    # rpc
    rpc-http-enabled=true
    rpc-http-host="0.0.0.0"
    rpc-http-port=8545
    rpc-http-api=["ADMIN", "DEBUG", "NET", "ETH", "MINER", "WEB3", "QBFT", "CLIQUE", "EEA", "IBFT"]
    rpc-http-cors-origins=["all"]

    # ws
    rpc-ws-enabled=false

    # graphql
    graphql-http-enabled=false

    # metrics
    metrics-enabled=true
    metrics-host="0.0.0.0"
    metrics-port=9545

    # permissions
    permissions-nodes-config-file-enabled=true
    permissions-nodes-config-file="/config/permissioned-nodes.toml"

    # static nodes
    static-nodes-file="/config/static-nodes.json"

    # miner
    # miner-enabled=true
