apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: besu

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - service-rpc.yaml
  - service-validator.yaml
  - sts-rpc.yaml
  - sts-validator.yaml

images:
  - name: hyperledger/besu
    newTag: 22.4.2

commonLabels:
  app.kubernetes.io/name: besu
