---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rpc
  namespace: besu
  labels:
    app.kubernetes.io/name: besu
    app.kubernetes.io/component: rpc
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: besu
      app.kubernetes.io/component: rpc
  serviceName: rpc
  replicas: 2
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: besu
      labels:
        app.kubernetes.io/name: besu
        app.kubernetes.io/component: rpc
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: besu
          securityContext: {}
          image: hyperledger/besu:22.4.1
          imagePullPolicy: IfNotPresent
          ports:
            - name: json-rpc
              containerPort: 8545
              protocol: TCP
            - name: ws
              containerPort: 8546
              protocol: TCP
            - name: graphql
              containerPort: 8547
              protocol: TCP
            - name: rlpx
              containerPort: 30303
              protocol: TCP
            - name: discovery
              containerPort: 30303
              protocol: UDP
            - name: metrics
              containerPort: 9545
              protocol: TCP
          # readinessProbe:
          #   httpGet:
          #     path: /readiness
          #     port: 8545
          livenessProbe:
            httpGet:
              path: /liveness
              port: 8545
            initialDelaySeconds: 180
            periodSeconds: 60
          resources: {}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: BESU_IDENTITY
              value: $(POD_NAME)
          volumeMounts:
            - name: data
              mountPath: /data
            - name: besu-config
              mountPath: /config
            - name: besu-secret
              mountPath: /keys/nodekey
              subPathExpr: $(POD_NAME).nodekey
          args:
            - --config-file=/config/config.toml
            - --Xdns-enabled=true
            - --Xdns-update-enabled=true
      volumes:
        - name: besu-config
          configMap:
            name: besu
        - name: besu-secret
          secret:
            secretName: besu
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          app.kubernetes.io/name: besu
          app.kubernetes.io/component: rpc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: '1Gi'
