apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: geth

resources:
- namespace.yaml
- configmap.yaml
- secret.yaml
- service-rpc.yaml
- service-signer.yaml
- sts-rpc.yaml
- sts-signer.yaml

images:
  - name: ethereum/client-go
    newTag: release-1.10

commonLabels:
  app.kubernetes.io/name: geth
